"""transaction

Revision ID: 0a1e8f2d1f13
Revises: 16269762b4c0
Create Date: 2023-12-17 18:39:00.653288

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a1e8f2d1f13"
down_revision = "16269762b4c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column(
            "amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Amount",
        ),
        sa.Column(
            "transaction_date",
            sa.DateTime(),
            nullable=False,
            comment="Transaction date",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="ID"),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation date",
        ),
        sa.Column(
            "update_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Update date",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Active flag"),
        sa.CheckConstraint("amount > 0", name="ck_amount"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.create_index("idx_id_transaction", ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_index("idx_id_transaction")

    op.drop_table("transaction")
    # ### end Alembic commands ###
