"""person_account

Revision ID: 16269762b4c0
Revises: 5c8d928723fc
Create Date: 2023-12-17 18:37:34.047985

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16269762b4c0"
down_revision = "5c8d928723fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("person_id", sa.Integer(), nullable=False, comment="Person ID")
        )
        batch_op.create_foreign_key(
            "fk_person_id",
            "person",
            ["person_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_constraint("fk_person_id", type_="foreignkey")
        batch_op.drop_column("person_id")

    # ### end Alembic commands ###
