"""person

Revision ID: 1a59032b7cb9
Revises: 3c1a8b70ec5c
Create Date: 2023-12-16 03:09:17.486994

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1a59032b7cb9"
down_revision = "3c1a8b70ec5c"
branch_labels = None
depends_on = None


def dowgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_account_id_account_type", table_name="account")
    op.drop_index("idx_person_id", table_name="account")
    op.drop_table("account")
    op.drop_index("idx_id_person", table_name="person")
    op.drop_table("person")
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person",
        sa.Column(
            "id_person",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
            comment="Person ID",
        ),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False, comment="Name"),
        sa.Column(
            "document", mysql.VARCHAR(length=14), nullable=False, comment="Document"
        ),
        sa.Column("birthday", mysql.DATETIME(), nullable=False, comment="Birthday"),
        sa.Column(
            "id",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "creation_date",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Creation date",
        ),
        sa.Column(
            "update_date",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Update date",
        ),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
            comment="Active flag",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_index("idx_id_person", "person", ["id_person"], unique=False)

    # ### end Alembic commands ###
