"""person

Revision ID: 3a2d81fc3285
Revises: 
Create Date: 2023-12-17 18:35:55.092477

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a2d81fc3285"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    person = op.create_table(
        "person",
        sa.Column("name", sa.String(length=255), nullable=False, comment="Name"),
        sa.Column("document", sa.String(length=14), nullable=False, comment="Document"),
        sa.Column("birthday", sa.DateTime(), nullable=False, comment="Birthday"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="ID"),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation date",
        ),
        sa.Column(
            "update_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Update date",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Active flag"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document", name="uq_person_document"),
        sa.UniqueConstraint("id", "document", name="uq_id_person_document"),
    )
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.create_index("idx_id_person", ["id"], unique=False)

    op.bulk_insert(
        person,
        [
            {
                "name": "John Doe",
                "document": "12345678901",
                "birthday": "1990-01-01",
                "is_active": True,
            },
            {
                "name": "Jane Doe",
                "document": "12345678902",
                "birthday": "1990-01-01",
                "is_active": True,
            },
        ],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.drop_index("idx_id_person")

    op.drop_table("person")
    # ### end Alembic commands ###
