"""account

Revision ID: 3c1a8b70ec5c
Revises: 
Create Date: 2023-12-16 01:56:48.845449

"""

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3c1a8b70ec5c"
down_revision = None
branch_labels = None
depends_on = None


def dowgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_account_id_account_type", table_name="account")
    op.drop_index("idx_person_id", table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column(
            "account_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
            comment="Account ID",
        ),
        sa.Column(
            "person_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
            comment="Person ID",
        ),
        sa.Column(
            "balance",
            mysql.DECIMAL(precision=10, scale=2),
            nullable=False,
            comment="Balance",
        ),
        sa.Column(
            "daily_withdrawal_limit",
            mysql.DECIMAL(precision=10, scale=2),
            nullable=False,
            comment="Daily withdrawal limit",
        ),
        sa.Column(
            "account_type",
            mysql.ENUM("CURRENT_ACCOUNT", "SAVINGS_ACCOUNT"),
            nullable=False,
            comment="Account type",
        ),
        sa.Column(
            "id",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "creation_date",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Creation date",
        ),
        sa.Column(
            "update_date",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Update date",
        ),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
            comment="Active flag",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_index("idx_person_id", "account", ["person_id"], unique=False)
    op.create_index(
        "idx_account_id_account_type",
        "account",
        ["account_id", "account_type"],
        unique=False,
    )
    # ### end Alembic commands ###
