"""transaction_account

Revision ID: 73ce2034d663
Revises: 0a1e8f2d1f13
Create Date: 2023-12-17 18:42:48.837025

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "73ce2034d663"
down_revision = "0a1e8f2d1f13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=False))
        batch_op.create_index("idx_account_id", ["account_id"], unique=False)
        batch_op.create_unique_constraint(
            "uq_account_transaction_date", ["account_id", "transaction_date"]
        )
        batch_op.create_foreign_key("fk_account_id", "account", ["account_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_constraint("fk_account_id", type_="foreignkey")
        batch_op.drop_constraint("uq_account_transaction_date", type_="unique")
        batch_op.drop_index("idx_account_id")
        batch_op.drop_column("account_id")

    # ### end Alembic commands ###
